# Generated by Django 3.2.25 on 2024-07-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmetrics',
            name='phished',
        ),
    ]
